// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_UfW50Ud5KAqSuKBsxMRYXjx5TM2Hjk',
    appId: '1:11760296659:web:5582fcaa2dbd4ce513ea26',
    messagingSenderId: '11760296659',
    projectId: 'privatemessenger-560cd',
    authDomain: 'privatemessenger-560cd.firebaseapp.com',
    storageBucket: 'privatemessenger-560cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Uy1a1eaLBqYhLtmQhpuzCcUInCbDAJY',
    appId: '1:11760296659:android:424e6c80b982907d13ea26',
    messagingSenderId: '11760296659',
    projectId: 'privatemessenger-560cd',
    storageBucket: 'privatemessenger-560cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2Yj08r5NrfFx-F23zBXuBHzIkkabds8',
    appId: '1:11760296659:ios:9d9c83f2f853ec2013ea26',
    messagingSenderId: '11760296659',
    projectId: 'privatemessenger-560cd',
    storageBucket: 'privatemessenger-560cd.appspot.com',
    iosBundleId: 'com.sambcorporation.privateMessenger',
  );
}
